### ISSUE TITLE
[BUG] Error after clicking previous semester in Timetable tab

### ISSUE THREAD

**Issue by sboh1214** [sparcs-kaist/otl-app#11]
## Description
사용자가 입학하기 이전의 학기에 진입을 시도하면 에러가 발생하는 것 같습니다.

## Screenshot
| Before Click | After Click |
|-------------|------------|
|<img width="564" alt="스크린샷 2021-08-11 오전 1 57 26" src="https://user-images.githubusercontent.com/30364442/128902508-32de4d08-8879-4e0d-bfb9-e5815cefc4b3.png">|<img width="564" alt="스크린샷 2021-08-11 오전 1 57 30" src="https://user-images.githubusercontent.com/30364442/128902527-07d46931-825f-4c4b-bee4-8191d7c2a497.png">|

## Error Log
```
Another exception was thrown: RangeError (index): Invalid value: Valid value range is
empty: 0
```

**Comment by sboh1214** [comment]
1.2.4 버전에서 여전히 오류 존재.
시간표가 하나도 존재하지 않는 학기로 이동 시 시간표 배열 RangeError 발생

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following RangeError was thrown building TimetablePage(dirty, dependencies:
flutter: [_InheritedProviderScope<TimetableModel?>], state: _TimetablePageState#dfbd5):
flutter: RangeError (index): Invalid value: Valid value range is empty: 0
flutter:
flutter: The relevant error-causing widget was:
flutter:   TimetablePage TimetablePage:file:///Users/sboh1214/Repos/otl-app/lib/home.dart:69:11
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      List.[] (dart:core-patch/growable_array.dart:254:60)
flutter: #1      TimetableModel.currentTimetable (package:otlplus/providers/timetable_model.dart:26:48)
flutter: #2      _TimetablePageState._buildBody.<anonymous closure> (package:otlplus/pages/timetable_page.dart:42:26)
flutter: #3      SelectContext.select (package:provider/src/inherited_provider.dart:283:32)
flutter: #4      _TimetablePageState._buildBody (package:otlplus/pages/timetable_page.dart:41:30)
flutter: #5      _TimetablePageState.build (package:otlplus/pages/timetable_page.dart:34:14)
flutter: #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:4782:27)
flutter: #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4665:15)
flutter: #8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840:11)
flutter: #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4355:5)
flutter: #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:33)
flutter: #11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
flutter: #12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
flutter: #13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
flutter: #14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
flutter: #15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
flutter: #19     _invoke (dart:ui/hooks.dart:166:10)
flutter: #20     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
flutter: #21     _drawFrame (dart:ui/hooks.dart:129:31)
flutter: (elided 3 frames from dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by sboh1214** [comment]
- 서버에서 해당 학기의 시간표를 불러올 때, 시간표가 한 개도 존재하지 않는다면 시간표 생성 요청을 클라이언트에서 보내야 한다.
- 유저가 시간표 삭제를 원하는 경우, 클라이언트에서 마지막 시간표인지 확인한다.
